Python API: tell function is read-only in setter instead of not found
When setting the value of an attribute which happens to be a function an `AttributeError` is raised. This error tells users that the attribute is not found, which may be confusing if the function is mentioned in the Blender API. Instead, tell that the attribute is read-only.

This is only done for RNA functions which are defined.

This matches what Python does when setting a function to a different value, e.g:

```
>>> "".join = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object attribute 'join' is read-only
```

Example with `bpy.context.selected_objects[0].shape_keys_selected = None`:

Before:
```
AttributeError: 'Object' object has no attribute 'shape_keys_selected'
```

After:
```
AttributeError: bpy_struct: attribute "shape_keys_selected" from "Object" is read-only
```

Ref: #157747