Operator Handlers. On bpy.props.CollectionProperty operator param, the callbak get the bpy_struct at first position.
The values are still set next, because the object is not iterable

```
TypeError: 'CollectionProperty' object is not iterable
```