Solves compiler errors using 'gcc version 12.2.0'
error: ‘INT_MAX’ was not declared in this scope

compiler hints to include missing header `#include <climits>`  but replaced with `std::numeric_limits<int>::max()` / min , *ONLY* in cases where the errors was thrown (there are more INT_MAX / INT_MIN usages around.